### ISSUE TITLE
Can this be used without the plugins/components.js requirement?

### ISSUE THREAD

**Issue by liamb13** [Dawntraoz/atomic-design-storyblok#326]
Wondering if it's possible to use atomic design structure with the StoryblokComponent to remove the components plugin requirement?

**Comment by liamb13** [comment]
Possible with: https://blok.blokwise.io

**Comment by Dawntraoz** [comment]
Hi @liamb13, just to clarify, this project was an example for a talk I made almost 1 year a half ago, so of course nowadays things have changed and are easier and more performant 🎉

We have really nice demos/boilerplates up-to-date at [Storyblok GitHub profile](https://github.com/storyblok), feel free to use the design/components from this repo if you want something 💜
